site_name: Game Design Docs
site_url: https://lushimi.github.io/FJN_Design/
theme:
  logo: Images/logo.webp
  name: material
  palette:
  - scheme: default
    primary: teal
    accent: deep orange
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: slate
    primary: teal
    accent: deep orange
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode

  features:
    - navigation.sections
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit

repo_url: https://github.com/Lushimi/FJN_Design
repo_name: Lushimi/FJN_Design

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true


docs_dir: Documents

plugins:
   - search
   - awesome-nav

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js