name: Add open issues to Bungi project

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add To GitHub projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          # You can target a project in a different organization
          # to the issue
          project-url: https://github.com/users/Lushimi/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}



name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install mkdocs-material

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
